CC_0		equ 0x00
CC_1		equ 0x01
CC_2		equ 0x02
CC_3		equ 0x03
CC_4		equ 0x04
CC_5		equ 0x05
CC_6		equ 0x06
CC_7		equ 0x07
CC_8		equ 0x08
CC_9		equ 0x09
CC_A		equ 0x0A
CC_B		equ 0x0B
CC_C		equ 0x0C
CC_D		equ 0x0D
CC_E		equ 0x0E
CC_F		equ 0x0F
CC_G		equ 0x10
CC_H		equ 0x11
CC_I		equ 0x12
CC_J		equ 0x13
CC_K		equ 0x14
CC_L		equ 0x15
CC_M		equ 0x16
CC_N		equ 0x17
CC_O		equ 0x18
CC_P		equ 0x19
CC_Q		equ 0x1A
CC_R		equ 0x1B
CC_S		equ 0x1C
CC_T		equ 0x1D
CC_U		equ 0x1E
CC_V		equ 0x1F
CC_W		equ 0x20
CC_X		equ 0x21
CC_Y		equ 0x22
CC_Z		equ 0x23
CC_LQ		equ 0x24	;`
CC_DSH		equ 0x25        ;-
CC_EQ		equ 0x26	;=
CC_LSB		equ 0x27        ;[
CC_RSB		equ 0x28        ;]
CC_AP		equ 0x29	;'
CC_CM		equ 0x2A	;,
CC_FS		equ 0x2B	;.
CC_WS		equ 0x2C	;\
CC_US		equ 0x2D	;/
CC_SC		equ 0x2E	;;
CC_SP		equ 0x2F	;SPACE
CC_TAB		equ 0x30	;TAB
CC_ENTER	equ 0x31	;ENTER
CC_KPE          equ 0x32        ;Key pad ENTER
CC_DEL		equ 0x33	;DELETE
CC_BKSP		equ 0x34	;BACKSPACE

CC_ESC		equ 0x80	;ESCAPE
CC_F1		equ 0x81
CC_F2		equ 0x82
CC_F3		equ 0x83
CC_F4		equ 0x84
CC_F5		equ 0x85
CC_F6		equ 0x86
CC_F7		equ 0x87
CC_F8		equ 0x88
CC_F9		equ 0x89
CC_F10		equ 0x8A
CC_F11		equ 0x8B
CC_F12		equ 0x8C
CC_PRINT	equ 0x8D
CC_SCROLL	equ 0x8E
CC_PAUSE	equ 0x8F
CC_NUM		equ 0x90
CC_CAPS		equ 0x91
CC_LSHIFT       equ 0x92
CC_RSHIFT       equ 0x93
CC_CTRL		equ 0x94
CC_CTRLR        equ 0x95
CC_ALT		equ 0x96
CC_ALTR         equ 0x97
CC_GUIL		equ 0x98
CC_GUIR		equ 0x99
CC_APPS		equ 0x9A
CC_INS          equ 0x9B
CC_HOME         equ 0x9C
CC_END          equ 0x9D
CC_PGUP         equ 0x9E
CC_PGDN         equ 0x9F
CC_PSF          equ 0xA0
CC_PSR          equ 0xA1
; A3 is £ symbol in character set, don't use it here
CC_LEFT         equ 0xA4
CC_RIGHT        equ 0xA5
CC_UP           equ 0xA6
CC_DOWN         equ 0xA7
; media keys
CC_MNXT         equ 0xA7        ; media next
CC_MPRV         equ 0xA8        ; media previous
CC_MPP          equ 0xA9        ; media play/pause
CC_MSTP         equ 0xAA        ; media stop
CC_MMT          equ 0xAB        ; media mute
CC_MVU          equ 0xAC        ; media volume up
CC_MVD          equ 0xAD        ; media volume down
CC_MSL          equ 0xAE        ; media select
CC_MEM          equ 0xAF        ; media email
; B0 is the degrees symbol, mapped to a key
CC_MCLC         equ 0xB1        ; media calculator
CC_MCMP         equ 0xB2        ; media my computer
CC_MSRCH        equ 0xB3        ; media web search
CC_MHOME        equ 0xB4        ; media web home
CC_MBCK         equ 0xB5        ; media web back
CC_MFWD         equ 0xB6        ; media web forward
CC_MWSP         equ 0xB7        ; media web stop
CC_MRFSH        equ 0xB8        ; media web refresh
CC_MFV          equ 0xB9        ; media web favourites
; acpi control codes
CC_PWR          equ 0xBA        ; power
CC_SLP          equ 0xBB        ; sleep
CC_WK           equ 0xBC        ; wake

CC_KP0		equ 0xC0
CC_KP1		equ 0xC1
CC_KP2		equ 0xC2
CC_KP3		equ 0xC3
CC_KP4		equ 0xC4
CC_KP5		equ 0xC5
CC_KP6		equ 0xC6
CC_KP7		equ 0xC7
CC_KP8		equ 0xC8
CC_KP9		equ 0xC9
CC_KPD		equ 0xCA	;.
CC_KPS		equ 0xCB	;*
CC_KPP		equ 0xCC	;+
CC_KPM		equ 0xCD	;-
CC_KPSL         equ 0xCE        ;/
